baseURL: "https://eternalfrustation.github.io"
title: EternalFrustAtion
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: EternalFrustAtion
  description: "Student with a passion for computers"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "https://images.google.com/images/branding/googlelogo/1x/googlelogo_light_color_272x92dp.png"
    favicon16x16: "https://images.google.com/images/branding/googlelogo/1x/googlelogo_light_color_272x92dp.png"
    favicon32x32: "https://images.google.com/images/branding/googlelogo/1x/googlelogo_light_color_272x92dp.png"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "EternalFrustAtion"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: EternalFrustAtion
    subtitle: "Student with a passion for Computers"
    imageUrl: "profile.png"
    imageWidth: 240
    imageHeight: 240
    imageTitle: my image
    buttons:
      - name: Projects
        url: projects
      - name: Blog
        url: posts

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: youtube
      url: "https://www.youtube.com/@codinginquarantine3420/"
    - name: github
      url: "https://github.com/EternalFrustAtion"

  analytics:
    google:
      SiteVerificationTag: "G-6213R1WW0M"

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: Projects
      name: Projects
      url: /projects/
      weight: 10
    - identifier: Blog
      name: Blog
      url: /posts/
      weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: dracula
